namespace UncomplicatedCustomAbilities.LIL.Enums
{
    public enum OpCodeType
    {
        Defcf,
        Ldref,
        Evalfr,
        Ldfld,
        Defvar,
        Call,
        Callvir,
        Stloc,
        Ldloc,
        Ldc,
        Ldop,
        Evalif,
        Evalfo,
        Evalwh,
        Defass,
        Ldstr,
        Strpop,
        Strc,
        Pop,
        Ldnum,
        Ldbool,
        Clear,
        Ret,
        Brk,
        Cont
    }
}
